### ISSUE TITLE
bb_lookup function

### ISSUE THREAD

**Issue by Robinlovelace** [hrbrmstr/nominatim#1]
Nominatim allows you to ask for the bounding box of any text string, e.g. (see [here](https://help.openstreetmap.org/questions/36323/how-to-export-country-bounding-boxes)):

https://nominatim.openstreetmap.org/search?q=United+Kingdom&format=xml

can we create a function called `bb_lookup()` that returns a `bbox` class object for any country/city/region.

It can even find the bb of quite complex regions, such as Yorkshire and the Humber
https://nominatim.openstreetmap.org/search.php?q=Yorkshire+and+the+Humber&viewbox=-78.53%2C42.55%2C-78.42%2C42.51

And West Yorkshire
https://nominatim.openstreetmap.org/search.php?q=West+Yorkshire&viewbox=-4.37%2C54.88%2C2.04%2C52.96

Started looking at this but not sure how best to start - any pointers and I can try. Otherwise more than happy to just test your code!

That would be sooooo useful for many applications, not least our overpass package :-)

**Comment by hrbrmstr** [comment]
oh this is super easy. gimme a bit.

**Comment by hrbrmstr** [comment]
done in latest push to master (just now)

**Comment by Robinlovelace** [comment]
Yes that returns the data but not in a form that's super easy to use... Can we add options to return only the 1st result (note your example `bb_lookup("United States")` returns 7 row, 6 of which are useless!)? Also I started writing an additional argument `bbox_only` so that only a single bounding box object is returned. That would be really handy. Shall I have a bash and put in a PR are do you want this one? probz a 5 minute job for you :)

**Comment by hrbrmstr** [comment]
I noticed the same thing when actually trying to _use_ the function :-) It'll be quick on my end.
