### ISSUE TITLE
Errors with osm_geocode()

### ISSUE THREAD

**Issue by Robinlovelace** [hrbrmstr/nominatim#5]
Reproducible example:

```
osm_geocode(c("1600 Pennsylvania Ave, Washington, DC.",
+     "1600 Amphitheatre Parkway, Mountain View, CA",
+     "Seattle, Washington"))
  |                                                  |   0%
Error connecting to geocode serviceError in doTryCatch(return(expr), name, parentenv, handler): client error: (403) Forbidden
```

Just tried on two separate computers. Any ideas?

**Comment by hrbrmstr** [comment]
I tried it yesterday for something and got the same error. Was going to
debug tomorrow (travel + running an R workshop in Pittsburgh today).

I suspect they may be blocking the user agent which may mean I need to
randomize it if some ne'er do well abused the service.

**Comment by rCarto** [comment]
Mapquest just introduced a key/account system in their API services.

**Comment by Robinlovelace** [comment]
Note: ggmap::geocode() also seems to broken.

**Comment by hrbrmstr** [comment]
Thx. I'll get it adapted asap.

**Comment by hrbrmstr** [comment]
I just sucked in @rCarto's PR so one can specify alternate servers and will be changing defaults (which will burden the osm servers but hey) and also figuring out how to allow for using mapquest (I just got an API key) since it's still the preferred way and 15K reqs a month is pretty generous for free.

**Comment by iskandari** [comment]
I receive this error when trying to geocode: `Error connecting to geocode serviceError in doTryCatch(return(expr), name, parentenv, handler): client error: (403) Forbidden`

**Comment by imlearningr** [comment]
I received the same error today when I used the reverse_geocode_coords function . Is there any update or solution please? thank you so much!

"Error connecting to geocode serviceError in doTryCatch(return(expr), name, parentenv, handler): Forbidden (HTTP 403)."

**Comment by raveem** [comment]
20th April 2016, same error. I thought it was my code, but even the stock example doesn't work.

**Comment by Rawrqs** [comment]
I tried to use simple example today `osm_search('Cracow University of Economics')`, but this didn't work for me.
I get an error: 

> Please provide a openstreet API key

I tried to specify the `key` parameter as my email address from OSM account.
I don't want to use the Mapquest API instead

Any solution to that?

**Comment by naumov-vladimir** [comment]
This issue should be reopened because I experience the same error (403) even with OSM API key.

**Comment by harleylang** [comment]
Go to mapquest and get a free api key: https://developer.mapquest.com/

Then run the command like `osm_search('London, Uk', key='yourkeyhere')`
