### ISSUE TITLE
Please provide a openstreet API key

### ISSUE THREAD

**Issue by kintero** [hrbrmstr/nominatim#7]
Hello,
The function osm_geocode always return me an error with this messages: "Please provide a openstreet API key".
Where can I get a openstreet API key?
Thanks,

**Comment by hrbrmstr** [comment]
The README for this repository has a link to the nominatim service where you can request an API key. http://open.mapquestapi.com/nominatim/

**Comment by LennertSchepers** [comment]
It would indeed be useful to mention in the documentation

- that you need an API key

- how you can get an API key (I found it in the help files: https://developer.mapquest.com)

- How you can store the API key: e.g. I've used this code:

`R.utils::setOption("OSM_API_KEY", "yourkey")`

**Comment by hrampadarath** [comment]
The comment by LennertSchepers should really be in the documentation. Was easier than searching through http://open.mapquestapi.com/nominatim/ for the answer.
